target-version = "py313"
line-length = 100
extend-exclude = ["core/migrations"]

[lint]
select = [
    "B",
    "BLE",
    "DTZ",
    "E4",
    "E7",
    "E9",
    "F",
    "I",
    "ISC",
    "RUF012",
    "RUF022",
    "RUF100",
    "S102",
    "S110",
    "S112",
    "SIM",
    "TRY401",
    "UP",
]

[lint.per-file-ignores]
"config/test_settings.py" = ["F403", "F405"]
"core/admin.py" = ["RUF012"]
"core/forms.py" = ["RUF012"]
"core/models.py" = ["RUF012"]
