# Generated by Django 5.2.16 on 2026-07-29 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_station_module_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTeamNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("note", models.CharField(max_length=200, verbose_name="Team")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="handoverentry",
            name="for_date",
            field=models.DateField(
                blank=True,
                help_text="Leer lassen fuer Allgemeines ohne Tagesbezug.",
                null=True,
                verbose_name="Betrifft Tag",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="location",
            field=models.CharField(blank=True, max_length=160, verbose_name="Standort"),
        ),
        migrations.AddIndex(
            model_name="handoverentry",
            index=models.Index(
                fields=["station", "for_date"], name="core_handov_station_b7b5cb_idx"
            ),
        ),
        migrations.AddField(
            model_name="dailyteamnote",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_team_notes",
                to="core.station",
            ),
        ),
        migrations.AddField(
            model_name="dailyteamnote",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyteamnote",
            constraint=models.UniqueConstraint(
                fields=("station", "date"), name="unique_station_day_team"
            ),
        ),
    ]
