# Generated by Django 5.2.16 on 2026-07-29 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_dailyteamnote_handoverentry_for_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedsource",
            name="station",
            field=models.ForeignKey(
                blank=True,
                help_text="Nur fuer stationsbezogene Quellen wie den Muellkalender gesetzt.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_sources",
                to="core.station",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="Ort"),
        ),
        migrations.AddField(
            model_name="station",
            name="district",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Kreis/Landkreis"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
        ),
        migrations.AddField(
            model_name="station",
            name="street",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Strasse und Hausnummer"
            ),
        ),
        migrations.AlterField(
            model_name="feedsource",
            name="attribution",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="feedsource",
            name="kind",
            field=models.CharField(
                choices=[
                    ("news_rss", "Nachrichten (RSS)"),
                    ("closure_csv", "Verkehrsmeldungen (CSV)"),
                    ("waste_ics", "Muellabfuhr (ICS)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedsource",
            name="locality",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name="feedsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "waste_ics")),
                fields=("station",),
                name="unique_station_waste_source",
            ),
        ),
    ]
