# Generated by Django 5.2.16 on 2026-07-31 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disable_feeds_after_module_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='tasks_enabled',
            field=models.BooleanField(default=True, verbose_name='Tagesaufgaben aktiviert'),
        ),
        migrations.CreateModel(
            name='StationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('band', models.CharField(choices=[('daily', 'Taeglich'), ('weekday', 'Wochentag'), ('extra', 'Zusaetzlich')], default='daily', max_length=20)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], help_text='Nur fuer Wochentagsaufgaben noetig (0=Montag).', null=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_tasks', to='core.station')),
            ],
            options={
                'ordering': ['band', 'weekday', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StationTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='station_task_completions', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='core.station')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.stationtask')),
            ],
            options={
                'ordering': ['-work_date', '-completed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stationtask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('band', 'weekday'), ('weekday__isnull', False)), models.Q(models.Q(('band', 'weekday'), _negated=True), ('weekday__isnull', True)), _connector='OR'), name='station_task_weekday_matches_band'),
        ),
        migrations.AddConstraint(
            model_name='stationtaskcompletion',
            constraint=models.UniqueConstraint(fields=('task', 'work_date'), name='unique_task_completion_day'),
        ),
    ]
