# Generated by Django 5.2.16 on 2026-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_feedsource_station_station_city_station_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="coffee_account_holder",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Kontoinhaber/in"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="coffee_iban",
            field=models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
        ),
        migrations.AddField(
            model_name="station",
            name="coffee_paypal_link",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="PayPal.me-Link"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="coffee_wero_link",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Wero-Zahlungslink oder -Kontakt",
            ),
        ),
    ]
