# Generated by Django 5.2.16 on 2026-07-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_station_coffee_account_holder_station_coffee_iban_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="onboarded",
            field=models.BooleanField(
                default=False, verbose_name="Einrichtung abgeschlossen"
            ),
        ),
    ]
