# Generated by Django 5.2.16 on 2026-07-29 14:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_station_onboarded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="coffee_iban",
            field=models.CharField(
                blank=True,
                max_length=34,
                validators=[core.models.validate_iban],
                verbose_name="IBAN",
            ),
        ),
    ]
