# Generated by Django 5.2.16 on 2026-07-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_registration_chat_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='holidays_enabled',
            field=models.BooleanField(default=True, verbose_name='Feiertage (NRW) im Kalender'),
        ),
    ]
