# Generated by Django 5.2.16 on 2026-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_station_coffee_iban"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="retention_audit_days",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Audit-Ereignisse loeschen nach (Tagen)"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="retention_calendar_days",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Vergangene Termine loeschen nach (Tagen)"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="retention_handover_days",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Erledigte Uebergaben loeschen nach (Tagen)"
            ),
        ),
    ]
