# Generated by Django 5.2.16 on 2026-07-31 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_holidays_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'Mitglied'), ('shift_lead', 'Schichtleitung'), ('cashier', 'Kassenwart'), ('admin', 'Master-Admin'), ('auditor', 'Auditor')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.BinaryField(blank=True, null=True)),
                ('avatar_content_type', models.CharField(blank=True, default='', max_length=32)),
                ('avatar_updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
