# Generated by Django 5.2.16 on 2026-07-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_handoveracknowledgement"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_active_membership",
        ),
    ]
