# Generated by Django 5.2.16 on 2026-07-31 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='algo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='key_wraps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='nonce',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='PrivateConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_conversations', to='core.station')),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_conversations_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_conversations_low', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciphertext', models.TextField()),
                ('nonce', models.CharField(max_length=64)),
                ('key_wraps', models.JSONField(default=dict)),
                ('algo', models.CharField(default='A256GCM+ECDH-ES', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_messages', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.privateconversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciphertext', models.TextField()),
                ('nonce', models.CharField(max_length=64)),
                ('key_wraps', models.JSONField(default=dict)),
                ('algo', models.CharField(default='A256GCM+ECDH-ES', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_secure_mails', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_mails', to='core.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureMailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.securemail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_secure_mails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCryptoIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_jwk', models.JSONField()),
                ('wrapped_private_jwk', models.TextField()),
                ('kdf_salt', models.CharField(max_length=128)),
                ('kdf_iterations', models.PositiveIntegerField(default=210000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='privateconversation',
            constraint=models.UniqueConstraint(fields=('station', 'user_low', 'user_high'), name='unique_private_conversation_pair'),
        ),
        migrations.AddConstraint(
            model_name='privateconversation',
            constraint=models.CheckConstraint(condition=models.Q(('user_low', models.F('user_high')), _negated=True), name='private_conversation_distinct_users'),
        ),
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['conversation', '-created_at'], name='core_privat_convers_93fabc_idx'),
        ),
        migrations.AddIndex(
            model_name='securemail',
            index=models.Index(fields=['station', '-created_at'], name='core_secure_station_4c28d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='securemailrecipient',
            constraint=models.UniqueConstraint(fields=('mail', 'user'), name='unique_secure_mail_recipient'),
        ),
    ]
