# Generated by Django 5.2.16 on 2026-07-30 04:41

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_totpdevice_recoverycode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="retention_task_days",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Erledigte Aufgaben loeschen nach (Tagen)"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="tasks_enabled",
            field=models.BooleanField(default=True, verbose_name="Aufgaben aktiviert"),
        ),
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="Name der Liste"),
                ),
                (
                    "rhythm",
                    models.CharField(
                        choices=[
                            ("weekdays", "An bestimmten Wochentagen"),
                            ("monthly", "Einmal im Monat"),
                        ],
                        default="weekdays",
                        max_length=20,
                        verbose_name="Rhythmus",
                    ),
                ),
                (
                    "weekdays",
                    models.CharField(
                        default="1234567",
                        max_length=7,
                        validators=[core.models.validate_weekdays],
                        verbose_name="Wochentage",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Faellt der Tag in einem Monat aus, gilt der letzte Tag des Monats.",
                        verbose_name="Tag im Monat",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_lists",
                        to="core.station",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Aufgabe")),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Optional, zum Beispiel wo etwas liegt oder worauf zu achten ist.",
                        max_length=300,
                        verbose_name="Hinweis",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.tasklist",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_runs",
                        to="core.station",
                    ),
                ),
                (
                    "task_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="core.tasklist",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="TaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("done", "Erledigt"),
                            ("defect", "Mangel"),
                            ("skipped", "Entfällt"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("recorded_at", models.DateTimeField(auto_now=True)),
                (
                    "handover",
                    models.ForeignKey(
                        blank=True,
                        help_text="Der Uebergabe-Eintrag, der aus einem Mangel entstanden ist.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_results",
                        to="core.handoverentry",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="core.taskitem",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.taskrun",
                    ),
                ),
            ],
            options={
                "ordering": ["item__position", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(
                fields=["station", "date"], name="core_taskru_station_b69021_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskrun",
            constraint=models.UniqueConstraint(
                fields=("task_list", "date"), name="unique_task_run_per_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskresult",
            constraint=models.UniqueConstraint(
                fields=("run", "item"), name="unique_task_result_per_item"
            ),
        ),
    ]
