# Generated by Django 5.2.16 on 2026-07-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_api_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='secret',
            field=models.CharField(max_length=255),
        ),
    ]
