# Generated by Django 5.2.16 on 2026-07-30 06:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_station_retention_task_days_station_tasks_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Bezeichnung")),
                ("start_time", models.TimeField(verbose_name="Beginn")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=1440,
                        help_text="1440 Minuten sind 24 Stunden, 720 Minuten sind 12 Stunden.",
                        verbose_name="Dauer in Minuten",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["position", "start_time", "pk"],
            },
        ),
        migrations.AlterModelOptions(
            name="dailyteamnote",
            options={"ordering": ["date", "shift__position", "shift__start_time"]},
        ),
        migrations.RemoveConstraint(
            model_name="dailyteamnote",
            name="unique_station_day_team",
        ),
        migrations.AddField(
            model_name="station",
            name="day_start_time",
            field=models.TimeField(
                default=datetime.time(7, 0),
                help_text="Uhrzeit, zu der auf dieser Wache der neue Wachentag anfaengt - in der Regel der Dienstbeginn der Fruehschicht. 00:00 bedeutet, dass der Wachentag dem Kalendertag entspricht.",
                verbose_name="Betriebstag beginnt um",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="task_attribution",
            field=models.CharField(
                choices=[
                    ("person", "Name der Person anzeigen"),
                    ("none", "Keinen Namen anzeigen (gemeinsames Wachengeraet)"),
                ],
                default="person",
                help_text="Haengt an der Wache ein gemeinsam genutztes Geraet, steht an jedem Haken derselbe Name. Dann ist es ehrlicher, gar keinen anzuzeigen.",
                max_length=10,
                verbose_name="Namen bei Aufgaben",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="core.station",
            ),
        ),
        migrations.AddField(
            model_name="dailyteamnote",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_notes",
                to="core.shift",
                verbose_name="Schicht",
            ),
        ),
        migrations.AddField(
            model_name="tasklist",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Leer lassen, wenn die Liste einmal je Wachentag gilt.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_lists",
                to="core.shift",
                verbose_name="Schicht",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyteamnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("shift__isnull", True)),
                fields=("station", "date"),
                name="unique_station_day_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyteamnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("shift__isnull", False)),
                fields=("station", "date", "shift"),
                name="unique_station_day_shift_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("station", "name"), name="unique_station_shift_name"
            ),
        ),
    ]
