# Generated by Django 6.0.7 on 2026-08-05 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_waste_calendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feeditem',
            new_name='feeditem_source_published',
            old_name='core_feedit_source__5ddf69_idx',
        ),
        migrations.RenameIndex(
            model_name='handoverentry',
            new_name='handover_station_status_created',
            old_name='core_handov_station_af30c6_idx',
        ),
        migrations.RenameIndex(
            model_name='pushoutbox',
            new_name='pushoutbox_status_next',
            old_name='core_pushou_status_0bbdae_idx',
        ),
        migrations.RenameIndex(
            model_name='pushoutbox',
            new_name='pushoutbox_station_status',
            old_name='core_pushou_station_d67423_idx',
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['station', 'starts_at'], name='calendar_station_starts'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['created_by', '-created_at'], name='calendar_created_by'),
        ),
        migrations.AddIndex(
            model_name='coffeeentry',
            index=models.Index(fields=['station', '-created_at'], name='coffee_station_created'),
        ),
        migrations.AddIndex(
            model_name='coffeeentry',
            index=models.Index(fields=['member', '-created_at'], name='coffee_member_created'),
        ),
        migrations.AddIndex(
            model_name='coffeeentry',
            index=models.Index(fields=['created_by', '-created_at'], name='coffee_created_by'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['-last_seen_at'], name='feeditem_last_seen'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['starts_on'], name='feeditem_starts_on'),
        ),
        migrations.AddIndex(
            model_name='handoverentry',
            index=models.Index(fields=['station', 'priority', '-created_at'], name='handover_station_priority'),
        ),
        migrations.AddIndex(
            model_name='handoverentry',
            index=models.Index(fields=['station', 'category'], name='handover_station_category'),
        ),
        migrations.AddIndex(
            model_name='handoverentry',
            index=models.Index(fields=['author', '-created_at'], name='handover_author_created'),
        ),
        migrations.AddIndex(
            model_name='pushoutbox',
            index=models.Index(fields=['user', 'status'], name='pushoutbox_user_status'),
        ),
        migrations.AddIndex(
            model_name='stationtaskcompletion',
            index=models.Index(fields=['station', 'work_date'], name='taskcomp_station_date'),
        ),
        migrations.AddIndex(
            model_name='stationtaskcompletion',
            index=models.Index(fields=['task', 'work_date'], name='taskcomp_task_date'),
        ),
        migrations.AddIndex(
            model_name='stationtaskcompletion',
            index=models.Index(fields=['completed_by', '-completed_at'], name='taskcomp_completed_by'),
        ),
    ]
