# Generated by Django 6.0.7 on 2026-08-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_normalize_inventory_constraint'),
    ]

    operations = [
        # HandoverEntry: Häufig gefiltert nach station+category, author+station
        migrations.AddIndex(
            model_name='handoverentry',
            index=models.Index(fields=['station', 'category'], name='idx_handover_station_category'),
        ),
        migrations.AddIndex(
            model_name='handoverentry',
            index=models.Index(fields=['author', 'station'], name='idx_handover_author_station'),
        ),
        migrations.AddIndex(
            model_name='handoverentry',
            index=models.Index(fields=['station', 'priority'], name='idx_handover_station_priority'),
        ),
        
        # CalendarEvent: Station + Datum
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['station', 'starts_at'], name='idx_calendar_station_starts'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['station', 'ends_at'], name='idx_calendar_station_ends'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['created_by', 'station'], name='idx_calendar_created_station'),
        ),
        
        # WasteCollection: Station + Datum
        migrations.AddIndex(
            model_name='wastecollection',
            index=models.Index(fields=['station', 'ends_at'], name='idx_waste_station_ends'),
        ),
        
        # BirthdayPreference: Station + Monat/Tag
        migrations.AddIndex(
            model_name='birthdaypreference',
            index=models.Index(fields=['station', 'month', 'day'], name='idx_birthday_station_date'),
        ),
        migrations.AddIndex(
            model_name='birthdaypreference',
            index=models.Index(fields=['user', 'station'], name='idx_birthday_user_station'),
        ),
        
        # CoffeeEntry: Station + Mitglied/Ersteller
        migrations.AddIndex(
            model_name='coffeeentry',
            index=models.Index(fields=['station', '-created_at'], name='idx_coffee_station_created'),
        ),
        migrations.AddIndex(
            model_name='coffeeentry',
            index=models.Index(fields=['member', 'station'], name='idx_coffee_member_station'),
        ),
        migrations.AddIndex(
            model_name='coffeeentry',
            index=models.Index(fields=['created_by', 'station'], name='idx_coffee_created_station'),
        ),
        
        # StationTask: Station + Band/Aktivität
        migrations.AddIndex(
            model_name='stationtask',
            index=models.Index(fields=['station', 'band'], name='idx_task_station_band'),
        ),
        migrations.AddIndex(
            model_name='stationtask',
            index=models.Index(fields=['station', 'is_active'], name='idx_task_station_active'),
        ),
        
        # StationTaskCompletion: Station + Datum
        migrations.AddIndex(
            model_name='stationtaskcompletion',
            index=models.Index(fields=['station', 'work_date'], name='idx_taskcomp_station_date'),
        ),
        migrations.AddIndex(
            model_name='stationtaskcompletion',
            index=models.Index(fields=['task', 'work_date'], name='idx_taskcomp_task_date'),
        ),
        migrations.AddIndex(
            model_name='stationtaskcompletion',
            index=models.Index(fields=['completed_by', 'station'], name='idx_taskcomp_user_station'),
        ),
        
        # FeedSource: Aktivitätsfilter
        migrations.AddIndex(
            model_name='feedsource',
            index=models.Index(fields=['is_enabled'], name='idx_feedsource_enabled'),
        ),
        
        # FeedItem: Quelle + Datum
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['source', 'last_seen_at'], name='idx_feeditem_source_seen'),
        ),
        
        # Membership: Station + Rolle/Aktivität
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['station', 'is_active'], name='idx_membership_station_active'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_active'], name='idx_membership_user_active'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['station', 'role'], name='idx_membership_station_role'),
        ),
        
        # PushOutbox: Status + Station
        migrations.AddIndex(
            model_name='pushoutbox',
            index=models.Index(fields=['station', 'status'], name='idx_pushoutbox_station_status'),
        ),
        migrations.AddIndex(
            model_name='pushoutbox',
            index=models.Index(fields=['user', 'station'], name='idx_pushoutbox_user_station'),
        ),
        
        # CalendarFeedToken: Station + Aktivität
        migrations.AddIndex(
            model_name='calendarfeedtoken',
            index=models.Index(fields=['station', 'is_active'], name='idx_feedtoken_station_active'),
        ),
        migrations.AddIndex(
            model_name='calendarfeedtoken',
            index=models.Index(fields=['created_by', 'station'], name='idx_feedtoken_created_station'),
        ),
        
        # ApiToken: User + Aktivität/Expiring
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['user', 'is_active'], name='idx_apitoken_user_active'),
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['user', 'expires_at'], name='idx_apitoken_user_expires'),
        ),
        
        # ChatMessage: Station + Autor
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['author', 'station'], name='idx_chat_author_station'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_hidden', 'station'], name='idx_chat_hidden_station'),
        ),
        
        # PrivateConversation: Station + Nutzer
        migrations.AddIndex(
            model_name='privateconversation',
            index=models.Index(fields=['station', '-updated_at'], name='idx_conv_station_updated'),
        ),
        
        # PrivateMessage: Conversation + Autor
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['author', 'conversation'], name='idx_pmsg_author_conv'),
        ),
        
        # SecureMail: Station + Sender
        migrations.AddIndex(
            model_name='securemail',
            index=models.Index(fields=['sender', 'station'], name='idx_securemail_sender_station'),
        ),
        
        # SecureMailRecipient: Mail + User
        migrations.AddIndex(
            model_name='securemailrecipient',
            index=models.Index(fields=['user', 'read_at'], name='idx_mailrecip_user_read'),
        ),
        
        # Checklist: Station + Aktivität
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['station', 'is_active'], name='idx_checklist_station_active'),
        ),
        
        # ChecklistCompletion: Station + Checkliste
        migrations.AddIndex(
            model_name='checklistcompletion',
            index=models.Index(fields=['checklist', 'station'], name='idx_checkcomp_checklist_station'),
        ),
        migrations.AddIndex(
            model_name='checklistcompletion',
            index=models.Index(fields=['completed_by', 'station'], name='idx_checkcomp_user_station'),
        ),
        
        # AuditEvent: Station + Aktion
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'station'], name='idx_audit_actor_station'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', 'station'], name='idx_audit_action_station'),
        ),
    ]
