# Generated by Django 6.0.7 on 2026-08-12 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_0022_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stationasset',
            name='inspection_interval_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationasset',
            name='last_inspected_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssetInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('ok', 'In Ordnung'), ('defect', 'Mangel festgestellt')], default='ok', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='core.stationasset')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_inspections', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_inspections', to='core.station')),
            ],
            options={
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['station', 'asset', '-performed_at'], name='inspection_station_idx')],
            },
        ),
    ]
