# Generated by Django 6.0.7 on 2026-08-11 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_0022_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='pinboard_enabled',
            field=models.BooleanField(default=True, verbose_name='Pinnwand aktiviert'),
        ),
        migrations.CreateModel(
            name='PinboardNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(max_length=2000)),
                ('category', models.CharField(choices=[('info', 'Info'), ('important', 'Wichtig'), ('event', 'Termin/Hinweis')], default='info', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinboard_notes', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinboard_notes', to='core.station')),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
                'indexes': [models.Index(fields=['station', 'is_archived', '-is_pinned', '-updated_at'], name='core_pinboa_station_49dfb2_idx')],
            },
        ),
    ]
