# Generated by Django 6.1 on 2026-10-09 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_station_organization_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='handoverack',
            name='unique_handover_user_ack',
        ),
        migrations.AddField(
            model_name='handoverack',
            name='version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='handoverack',
            constraint=models.UniqueConstraint(fields=('handover', 'user', 'version'), name='unique_handover_user_version_ack'),
        ),
    ]
