from django.urls import path

from . import views
from . import views_twofactor


urlpatterns = [
    path("zugang/", views.access, name="access"),
    path("impressum/", views.imprint, name="imprint"),
    path("datenschutz/", views.privacy, name="privacy"),
    path("barrierefreiheit/", views.accessibility, name="accessibility"),
    path("demo/", views.demo, name="demo"),
    path("demo/start/", views.demo_start, name="demo_start"),
    path("", views.dashboard, name="dashboard"),
    path("einrichtung/", views.setup_wizard, name="setup_wizard"),
    path("einrichtung/<str:step>/", views.setup_wizard, name="setup_wizard"),
    path("uebergaben/", views.handover_list, name="handover_list"),
    path("uebergaben/neu/", views.handover_create, name="handover_create"),
    path("uebergaben/<int:pk>/", views.handover_detail, name="handover_detail"),
    path("uebergaben/<int:pk>/bearbeiten/", views.handover_edit, name="handover_edit"),
    path("uebergaben/<int:pk>/gelesen/", views.handover_acknowledge, name="handover_acknowledge"),
    path("uebergaben/<int:pk>/status/", views.handover_status, name="handover_status"),
    path("wochenprotokoll/", views.handover_week, name="handover_week"),
    path("wochenprotokoll/pdf/", views.handover_week_pdf, name="handover_week_pdf"),
    path("wochenprotokoll/<str:tag>/team/", views.daily_team_update, name="daily_team_update"),
    path("kalender/", views.calendar_view, name="calendar"),
    path("kalender/neu/", views.calendar_create, name="calendar_create"),
    path("geburtstage/", views.birthdays, name="birthdays"),
    path("geburtstage/einstellung/", views.birthday_settings, name="birthday_settings"),
    path("kaffeekasse/", views.coffee, name="coffee"),
    path("kaffeekasse/neu/", views.coffee_create, name="coffee_create"),
    path("kaffeekasse/<int:pk>/korrigieren/", views.coffee_correct, name="coffee_correct"),
    path("kaffeekasse/zahlungsangaben/", views.coffee_payment_update, name="coffee_payment_update"),
    path("lage/", views.feeds, name="feeds"),
    path("lage/muellabfuhr/", views.waste_source_update, name="waste_source_update"),
    path("mehr/", views.more, name="more"),
    path("zwei-faktor/", views_twofactor.twofactor_status, name="twofactor_status"),
    path("zwei-faktor/einrichten/", views_twofactor.twofactor_setup, name="twofactor_setup"),
    path("zwei-faktor/codes/", views_twofactor.twofactor_codes, name="twofactor_codes"),
    path("zwei-faktor/codes/neu/", views_twofactor.twofactor_regenerate, name="twofactor_regenerate"),
    path("zwei-faktor/deaktivieren/", views_twofactor.twofactor_disable, name="twofactor_disable"),
    path("wache-wechseln/", views.switch_station, name="switch_station"),
    path("team/", views.team, name="team"),
    path("team/freigeben/", views.team_create, name="team_create"),
    path("team/<int:pk>/", views.membership_update, name="membership_update"),
    path("einstellungen/", views.station_settings, name="station_settings"),
    path("einstellungen/adresse/", views.station_geocode, name="station_geocode"),
    path("audit/", views.audit_log, name="audit_log"),
]
